export const FLIP_CARD_TO_OPENED = 'CARD/FLIP_CARD_TO_OPENED';
export const FLIP_CARD_TO_CLOSED = 'CARD/FLIP_CARD_TO_CLOSED';
export const FLIP_CARD_ADD_TO_CHECK = 'CARD/FLIP_CARD_ADD_TO_CHECK';
export const UPDATED_PLAYFIELD = 'CARD/UPDATED_PLAYFIELD';
export const INCREASE_ROUND_POINT = 'ROUND/INCREASE_ROUND_POINT';
